import Header from '@/components/common/Header/Header'
import '../styles/globals.scss'
import { Inter, Rubik } from 'next/font/google'
import ClientProvider from '@/modules/ClientProvider'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <main>
          <ClientProvider>
            {children}
          </ClientProvider>
        </main>
      </body>
    </html>
  )
}
