import Header from '@/components/common/Header/Header'
import '../styles/globals.scss'
import { Inter } from 'next/font/google'
import ClientProvider from '@/modules/ClientProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <ClientProvider>
            {children}
          </ClientProvider>
        </main>
      </body>
    </html>
  )
}
